(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-project-name "android")
 '(browse-url-browser-function 'browse-url-generic)
 '(browse-url-generic-program "/usr/bin/conkeror")
 '(jde-compile-enable-kill-buffer nil)
 '(jde-ant-enable-find t)
 '(jde-electric-return-p t)
 '(jde-ant-complete-target t)
 '(jde-enable-abbrev-mode t)
 '(jde-global-classpath '("./libs" "./bin/classes" "./src"))
 '(jde-run-working-directory "./")
 '(jde-ant-read-target t)
 '(jde-jdk-doc-url "http://developer.android.com/guide/topics/fundamentals.html")
 '(jde-compile-option-directory "./bin/classes")
 '(jde-complete-function (quote jde-complete-menu))
 '(jde-sourcepath '("./src"))
 '(jde-help-use-frames nil)
 '(jde-complete-insert-method-signature nil)
 '(jde-help-docsets (quote (("JDK API" "http://java.sun.com/javase/6/docs/api" nil)))))
